require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GuestlistsController do

  # This should return the minimal set of attributes required to create a valid
  # Guestlist. As you add validations to Guestlist, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GuestlistsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all guestlists as @guestlists" do
      guestlist = Guestlist.create! valid_attributes
      get :index, {}, valid_session
      assigns(:guestlists).should eq([guestlist])
    end
  end

  describe "GET show" do
    it "assigns the requested guestlist as @guestlist" do
      guestlist = Guestlist.create! valid_attributes
      get :show, {:id => guestlist.to_param}, valid_session
      assigns(:guestlist).should eq(guestlist)
    end
  end

  describe "GET new" do
    it "assigns a new guestlist as @guestlist" do
      get :new, {}, valid_session
      assigns(:guestlist).should be_a_new(Guestlist)
    end
  end

  describe "GET edit" do
    it "assigns the requested guestlist as @guestlist" do
      guestlist = Guestlist.create! valid_attributes
      get :edit, {:id => guestlist.to_param}, valid_session
      assigns(:guestlist).should eq(guestlist)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Guestlist" do
        expect {
          post :create, {:guestlist => valid_attributes}, valid_session
        }.to change(Guestlist, :count).by(1)
      end

      it "assigns a newly created guestlist as @guestlist" do
        post :create, {:guestlist => valid_attributes}, valid_session
        assigns(:guestlist).should be_a(Guestlist)
        assigns(:guestlist).should be_persisted
      end

      it "redirects to the created guestlist" do
        post :create, {:guestlist => valid_attributes}, valid_session
        response.should redirect_to(Guestlist.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved guestlist as @guestlist" do
        # Trigger the behavior that occurs when invalid params are submitted
        Guestlist.any_instance.stub(:save).and_return(false)
        post :create, {:guestlist => {}}, valid_session
        assigns(:guestlist).should be_a_new(Guestlist)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Guestlist.any_instance.stub(:save).and_return(false)
        post :create, {:guestlist => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested guestlist" do
        guestlist = Guestlist.create! valid_attributes
        # Assuming there are no other guestlists in the database, this
        # specifies that the Guestlist created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Guestlist.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => guestlist.to_param, :guestlist => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested guestlist as @guestlist" do
        guestlist = Guestlist.create! valid_attributes
        put :update, {:id => guestlist.to_param, :guestlist => valid_attributes}, valid_session
        assigns(:guestlist).should eq(guestlist)
      end

      it "redirects to the guestlist" do
        guestlist = Guestlist.create! valid_attributes
        put :update, {:id => guestlist.to_param, :guestlist => valid_attributes}, valid_session
        response.should redirect_to(guestlist)
      end
    end

    describe "with invalid params" do
      it "assigns the guestlist as @guestlist" do
        guestlist = Guestlist.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Guestlist.any_instance.stub(:save).and_return(false)
        put :update, {:id => guestlist.to_param, :guestlist => {}}, valid_session
        assigns(:guestlist).should eq(guestlist)
      end

      it "re-renders the 'edit' template" do
        guestlist = Guestlist.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Guestlist.any_instance.stub(:save).and_return(false)
        put :update, {:id => guestlist.to_param, :guestlist => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested guestlist" do
      guestlist = Guestlist.create! valid_attributes
      expect {
        delete :destroy, {:id => guestlist.to_param}, valid_session
      }.to change(Guestlist, :count).by(-1)
    end

    it "redirects to the guestlists list" do
      guestlist = Guestlist.create! valid_attributes
      delete :destroy, {:id => guestlist.to_param}, valid_session
      response.should redirect_to(guestlists_url)
    end
  end

end
